- name: Install Docker on Ubuntu 18.04
  hosts: all
  connection: ssh
  become: yes
  tasks:

  - name: apt update
    apt:
      update_cache: yes

  - name: Install prerequisites for Docker repository
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - nfs-common

  - name: add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
      update_cache: yes
  
  - name: install docker and it's dependencies
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: start and enable docker daemon
    service:
      name: docker
      state: started
      enabled: yes
  
  - name: fetch docker-compose checksum
    uri:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64.sha256
      return_content: yes
    register: docker_compose_checksum

  - name: install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      checksum: "sha256:{{ docker_compose_checksum.content.split(' ') | first }}"
      dest: /usr/local/bin/docker-compose
      mode: '0755'
