- name: Install Docker on Ubuntu 18.04
  hosts: all
  connection: ssh
  become: yes
  tasks:

  - name: apt update
    apt:
      update_cache: yes

  - name: Install prerequisites for Docker repository
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - nfs-common

  - name: add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
      update_cache: yes
  
  - name: install docker and it's dependencies
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      
  - name: Add "vmware" user to "docker" group
    user:
      name: "vmware"
      group: "docker"
      append: yes

  - name: Start and enable docker daemon
    service:
      name: docker
      state: started
      enabled: yes
  
  - name: Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: '0755'
